# Generated by Django 3.2.12 on 2022-06-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebook_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_surname', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phonebook.phonebook')),
            ],
        ),
    ]
