# Generated by Django 4.0.5 on 2022-06-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_rename_question_contact_contatc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contatc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.phonebook'),
        ),
    ]
